//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Farm_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Employee_Number { get; set; }
        public string Full_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Adress { get; set; }
        public int Position_Code { get; set; }
        public string Passport_Number { get; set; }
        public string Passport_Series { get; set; }
        public System.DateTime Birth_Date { get; set; }
    }
}
