//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Farm_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int Position_Code { get; set; }
        public string Position1 { get; set; }
        public int Department_Code { get; set; }
        public string Activity { get; set; }
    }
}
